#!/bin/bash
cd "$(dirname "$0")"
if [ ! -d "libs" ]; then
    mkdir libs
fi

if [ ! -d "debs" ];  then
    mkdir debs
fi

SOURCE="http://archive.ubuntu.com"
# Use the source below if you feel slow, or change it on your own.
# SOURCE="https://mirrors.ustc.edu.cn"

exit_succeed() {
  echo >&2 $1
  exit 0
}

exit_failed() {
  echo >&2 $1
  exit 1
}

exit_interrupt() {
  echo >&2 $1
  exit 2
}

usage() {
  echo >&2 "Usage: $0 <id> [source=http://archive.ubuntu.com]"
  echo >&2 "e.g.   $0 2.31-0ubuntu9.9_amd64"
  echo >&2 "       $0 2.35-0ubuntu3.1_amd64 https://mirrors.ustc.edu.cn"
  exit 3
}

download_single() {
  local id=$1
  local deb_name=$LIBC_PREFIX$id.deb
  local dbg_name=$LIBC_DBG_PREFIX$id.deb
  echo "Getting $id"
  if [ -d "libs/$id" ]; then
    exit_succeed "  --> Downloaded before."
  fi

  # download binary package
  local url="$SOURCE$deb_name"
  echo "  -> Location: $url"
  echo "  -> Downloading libc binary package"
  wget -c --tries=0 --retry-connrefused --timeout=10 --waitretry=5 -O debs/$deb_name $url
  if test $? -ne 0; then
    exit_failed "Failed to download package from $url"
  fi
  echo "  -> Extracting libc binary package"

  mkdir libs/$id
  ./extract debs/$deb_name libs/$id
  echo "  -> Package saved to libs/$id"

  # download debug info package
  local url="$SOURCE$dbg_name"
  echo "  -> Location: $url"
  echo "  -> Downloading libc debug package"
  wget -c --tries=0 --retry-connrefused --timeout=10 --waitretry=5 -O debs/$dbg_name $url
  if test $? -ne 0; then
    exit_failed "Failed to download package from $url"
  fi
  echo "  -> Extracting libc debug package"

  mkdir libs/$id/.debug
  ./extract debs/$dbg_name libs/$id/.debug
  exit_succeed "  -> Package saved to libs/$id/.debug"
}

if [[ $# != 1 ]]; then
  if [[ $# != 2 ]]; then
    usage
  fi
  SOURCE=$2
fi
if test ${SOURCE:0-1} != '/'; then
  SOURCE="$SOURCE/"
fi
SOURCE="${SOURCE}ubuntu/pool/main/g/glibc/"
echo "[!] Current source: $SOURCE"

LIBC_PREFIX="libc6_"
LIBC_DBG_PREFIX="libc6-dbg_"

trap 'exit_interrupt "Download interrupted."' INT
download_single "$1"
